version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0

parameters:
  secretval:
    type: string
    default: ""

jobs:
  initial:
    executor: gcp-cli/default
    resource_class: small
    steps:
      - checkout
      #- gcp-cli/install
      #- gcp-cli/initialize
      - run:
          name: Creating a secret
          command: |
            stty -echo; echo '<< pipeline.parameters.secretval >>' > /tmp/savecreds

workflows:
  testcci:
    jobs:
      - initial:
          context:
            - GCP-Vars