version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-cli: circleci/gcp-cli@2.4.0

executors:
  machexec:
    resource_class: medium
    machine:
      image: ubuntu-2204:2022.07.1

workflows:
  testmvncgcp:
    jobs:
      - create-secret-tag:
          context:
            - GCP-Vars
      - build-and-push:
          context: 
            - GCP-Vars
          requires:
            - create-secret-tag        

parameters:
  secretval:
    type: string
    default: "testhistag"

jobs:
  create-secret-tag:
    executor: machexec
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          name: Creating a secret
          command: |
            secretval=<< pipeline.parameters.secretval >>
            cat \<< EOF > savesecrets.sh
            #!/bin/bash
            echo $secretval > savesecrets.txt
            EOF
            chmod +x savesecrets.sh
            sh -c ./savesecrets.sh
            gcloud secrets create secret-tag --data-file=savesecrets.txt      
  build-and-push:
    executor: machexec
    steps:
      - checkout
      - gcp-cli/initialize
      - run: echo 'export SECTAG=$(gcloud secrets versions access 1 --secret="secret-tag")' >> "$BASH_ENV"
      - run: sudo apt install maven
      - run: mvn package
      - gcp-gcr/gcr-auth:
          registry-url: asia.gcr.io
      - gcp-gcr/build-image:
          image: petstore
          registry-url: asia.gcr.io
          tag: ${SECTAG}
      - gcp-gcr/push-image:
          image: petstore
          registry-url: asia.gcr.io
          tag: ${SECTAG}
