version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  machexec:
    machine:
      image: ubuntu-2204:2022.07.1

jobs:
  mvn:
    steps:
      - checkout
      - maven/test:
          executor: machexec
          command: package
  build-and-push:
    steps:
      - checkout
      - gcp-gcr/build-and-push-image:
          executor: machexec          
          image: test-image
          registry-url: ap.gcr.io

workflows:
  testcci:
    jobs:
      - mvn:          
          command: package
      - build-and-push:          
          context: GCP-Vars
          requires:
            - mvn       