version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-cli: circleci/gcp-cli@2.4.0

executors:
  machexec:
    resource_class: medium
    machine:
      image: ubuntu-2204:2022.07.1

workflows:
  testmvncgcp:
    jobs:
      - create-gke-cluster:
          context:
            - GCP-Vars

jobs:
  create-gke-cluster:
    executor: machexec
    steps:
      - checkout
      - gcp-cli/initialize
      - run: gcloud components install kubectl      
      - run: gcloud container clusters create-auto poc-cluster
      - run: gcloud container clusters get-credentials poc-cluster
      - run: kubectl get no      