version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0

jobs:
  initial:
    executor: gcp-cli/default
    resource_class: small
    parameters:
      secretval:
        type: string
        default: $SECRETVAL
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run: printf << parameters.secretval >> | gcloud secrets create ccisecret --data-file=-
          

workflows:
  testcci:
    jobs:
      - initial:
          context:
            - GCP-Vars