version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
jobs:
  initial:
    executor: gcp-cli/default
    resource_class: small
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Listing of projects
          command: |
            gcloud projects list

workflows:
  testcci:
    jobs:
      - initial:
          context:
            - GCP-Vars