version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

parameters:
  secretval:
    type: string
    default: ""

jobs:
  initializeGCP:
    executor: gcp-cli/default
    resource_class: small
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize

workflows:
  testcci:
    jobs:
      - initializeGCP:
          context: GCP-Vars
      - maven/test:
          command: -N io.takari:maven:wrapper -Dmaven=3.5.3
          requires:
            - initializeGCP          
      - gcp-gcr/build-and-push-image:
          context: GCP-Vars
          image: my-image
          registry-url: ap.gcr.io
          requires:
            - maven/test           