version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-cli: circleci/gcp-cli@2.4.0

executors:
  machexec:
    resource_class: medium
    machine:
      image: ubuntu-2204:2022.07.1

workflows:
  testmvncgcp:
    jobs:
      - extract-secret:
          context: 
            - GCP-Vars
      - build-and-push:
          context: 
            - GCP-Vars

jobs:
  extract-secret:
    executor: machexec
    steps:
      - checkout
      - gcp-cli/initialize
      - run: gcloud secrets versions access 1 --secret="secret-tag" >> sectext
      - run: echo 'export SECTAG=$(gcloud secrets versions access 1 --secret="secret-tag")' >> "$BASH_ENV"
      - run: pwd; ls -lrt
  build-and-push:
    executor: machexec
    steps:
      - checkout
      - run: sudo apt install maven
      - run: mvn package
      - run: pwd; ls -lrt
