version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-cli: circleci/gcp-cli@2.4.0

executors:
  machexec:
    resource_class: medium
    machine:
      image: ubuntu-2204:2022.07.1

workflows:
  testmvncgcp:
    jobs:
      - build-and-push:
          context: 
            - GCP-Vars

jobs:
  build-and-push:
    executor: machexec
    steps:
      - checkout
      - run: sudo apt install maven
      - run: mvn package
      - gcp-cli/initialize
      - run: gcloud secrets versions access 1 --secret="secret-tag" --project $GOOGLE_PROJECT_ID
      - run: echo 'export SECTAG=$(gcloud secrets versions access 1 --secret="secret-tag")' >> "$BASH_ENV"            
      - gcp-gcr/gcr-auth:
          registry-url: asia.gcr.io
      - gcp-gcr/build-image:
          image: petstore
          registry-url: asia.gcr.io
          tag: ${SECTAG}
      - gcp-gcr/push-image:
          image: petstore
          registry-url: asia.gcr.io
          tag: ${SECTAG}