version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  gcp-cli: circleci/gcp-cli@2.4.0

executors:
  machexec:
    resource_class: medium
    machine:
      image: ubuntu-2204:2022.07.1

workflows:
  testmvncgcp:
    jobs:      
      - deploy-to-gke:
          context: 
            - GCP-Vars

jobs:
  deploy-to-gke:
    executor: machexec
    steps:
      - checkout
      - gcp-cli/initialize
      - run: gcloud components install kubectl
      - run: gcloud container clusters get-credentials poc-cluster
      - run: kubectl get no
      - run: kubectl create deployment petstore --image=asia.gcr.io/$GOOGLE_PROJECT_ID/petstore:latest
      - run: kubectl expose deployment petstore --type LoadBalancer --port 80 --target-port 8080
