version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0

executors:
  machexec:
    resource_class: medium
    machine:
      image: ubuntu-2204:2022.07.1

workflows:
  testmvncgcp:
    jobs:
      - build-and-push:
          context: 
            - GCP-Vars

jobs:
  build-and-push:
    executor: machexec
    steps:
      - checkout
      - run: sudo apt install maven
      - run: pwd; ls -al
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: testimg
          tag: latest
      - gcp-gcr/push-image:
          image: testimg
          tag: latest
          registry-url: ap.gcr.io


