executors:
  machexec:
    machine:
      image: ubuntu-2204:2022.07.1
jobs:
  build-and-push:
    executor: machexec
    steps:
      - checkout
      - gcp-gcr/build-and-push-image:
          image: test-img
          registry-url: ap.gcr.io
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push
