version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  gcp-executor:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true


jobs:
  initializeGCP:
    executor: gcp-executor
    steps:
      - checkout
      - run:
          name: Set variable 
          command: |
            echo 'export CLOUDSDK_PYTHON="/opt/circleci/.pyenv/versions/3.10.5/bin/python3"' >> "$BASH_ENV"
            whereis python
            whereis python3
      - run:
          name: Check Variable
          command: |
            echo $CLOUDSDK_PYTHON
      - gcp-cli/install
      - gcp-cli/initialize

workflows:
  testcci:
    jobs:
      - initializeGCP:
          context: GCP-Vars
     