version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  gcp-executor:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true

jobs:
  mvn:
    steps:
      - checkout
      - maven/test:
          command: package
  build-and-push:
    steps:
      - checkout
      - gcp-gcr/build-and-push-image:          
          image: test-image
          registry-url: ap.gcr.io

workflows:
  testcci:
    jobs:
      - mvn:
          executor: gcp-executor
          command: package
      - build-and-push:
          executor: gcp-executor
          context: GCP-Vars
          requires:
            - mvn       