version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  gcp-executor:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    working_directory: /tmp

workflows:
  testcci:
    jobs:
      - maven/test:
          executor: gcp-executor
          command: package
          persist_to_workspace:
            root: workspace
            paths:
             - spring-boot-docker-maven.jar
      - gcp-gcr/build-and-push-image:
          executor: gcp-executor
          context: GCP-Vars
          image: my-image
          registry-url: ap.gcr.io
          attach_workspace:
            at: /tmp/workspace
          requires:
            - maven/test           