version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  machexec:
    machine:
      image: ubuntu-2204:2022.07.1

jobs:
  mvn:
    steps:
      - checkout
      - maven/test:
          command: package
  build-and-push:
    steps:
      - checkout
      - gcp-gcr/build-and-push-image:         
          image: test-image
          registry-url: ap.gcr.io

workflows:
  testcci:
    jobs:
      - mvn:
          executor:
            machine:
              image: ubuntu-2204:2022.07.1         
      - build-and-push:
          executor:
            machine:
              image: ubuntu-2204:2022.07.1 
          context: GCP-Vars
          requires:
            - mvn       