version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  poc-exec:
    docker:
      - image: cimg/python:3.10.7-node

workflows:
  testcci:
    jobs:
      - initializeGCP:
          context: GCP-Vars

jobs:
  initializeGCP:
    executor: poc-executor
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize