version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  gcp-executor:
    resource_class: medium
    working_directory: ~/testdir
    machine:
      - image: ubuntu-2004:current
        docker_layer_caching: true
    #working_directory: /tmp

parameters:
  secretval:
    type: string
    default: ""

jobs:
  initializeGCP:
    executor: gcp-executor
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize

workflows:
  testcci:
    jobs:
      - initializeGCP:
          context: GCP-Vars
      - maven/test:
          executor: gcp-executor
          command: package
          working_directory: /tmp
          requires:
            - initializeGCP          
      - gcp-gcr/build-and-push-image:
          executor: gcp-executor
          context: GCP-Vars
          image: my-image
          registry-url: ap.gcr.io
          requires:
            - maven/test           