version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  self-executor:
    machine: true
    resource_class: barishandcloud/selfresource

workflows:
  testcci:
    jobs:
      - initializeGCP:
          context: GCP-Vars

jobs:
  initializeGCP:
    executor: self-executor
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"