version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
jobs:
  initial:
    executor: gcp-cli/default
    resource_class: small
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: Creating a secret
          command: |
            printf "s3cr3t" | gcloud secrets create my-secret --data-file=-

workflows:
  testcci:
    jobs:
      - initial:
          context:
            - GCP-Vars