version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  gcp-executor:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true


jobs:
  initializeGCP:
    executor: gcp-executor
    steps:
      - checkout
      - run:
          name: Creating a secret
          command: |
            python --version
      - gcp-cli/install
      - gcp-cli/initialize

workflows:
  testcci:
    jobs:
      - initializeGCP:
          context: GCP-Vars
     