version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0

parameters:
  secretval:
    type: string
    default: ""

jobs:
  initial:
    executor: gcp-cli/default
    resource_class: small
    steps:
      - checkout
      #- gcp-cli/install
      #- gcp-cli/initialize
      - run:
          name: Creating a secret
          command: |
            secretval=<< pipeline.parameters.secretval >>
            cat \<< EOF > savesecrets.sh
            #!/bin/bash
            echo $secretval > savesecrets.txt
            EOF
            sh -c savesecrets.sh

workflows:
  testcci:
    jobs:
      - initial:
          context:
            - GCP-Vars