version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.15.0

parameters:
  secretval:
    type: string
    default: ""

jobs:
  initial:
    executor: gcp-cli/default
    resource_class: small
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize

workflows:
  testcci:
    jobs:
      - initial:
          context: GCP-Vars
      - gcp-gcr/build-and-push-image:
          context: GCP-Vars
          image: my-image
          registry-url: ap.gcr.io