version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
jobs:
  build:
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
workflows:
  version: 2.1
  testcci:
    jobs:
      - build