version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.0
  maven: circleci/maven@1.3.0

executors:
  machexec:
    machine:
      image: ubuntu-2204:2022.07.1

jobs:
  build-and-push:
    executor: machexec
    steps:
      - gcp-gcr/build-and-push-image:         
          image: test-image
          registry-url: ap.gcr.io

workflows:
  testcci:
    jobs:
      - build-and-push:
          context: GCP-Vars
          requires:
            - maven_test       